"use node";

/**
 * Fetch YouTube Video Captions Action
 *
 * Fetches caption/transcript data from YouTube videos when available.
 * Uses the YouTube Data API to list caption tracks and attempts to retrieve text.
 */

import { v } from "convex/values";
import { action } from "../../_generated/server";
import { isValidVideoId } from "../../lib/youtubeUrlParser";

/**
 * YouTube captions list response
 */
interface YouTubeCaptionsResponse {
  items?: {
    id: string;
    snippet: {
      videoId: string;
      lastUpdated: string;
      trackKind: string;
      language: string;
      name: string;
      audioTrackType: string;
      isCC: boolean;
      isLarge: boolean;
      isEasyReader: boolean;
      isDraft: boolean;
      isAutoSynced: boolean;
      status: string;
    };
  }[];
  error?: {
    code: number;
    message: string;
  };
}

/**
 * Fetch captions for a YouTube video
 *
 * Note: Due to YouTube API limitations, this returns caption track info.
 * The actual caption text requires OAuth authentication or alternative methods.
 * For recipe extraction, we primarily rely on video description.
 *
 * @param videoId - YouTube video ID
 * @returns Caption text if available, or null
 */
export const fetchCaptions = action({
  args: {
    videoId: v.string(),
  },
  handler: async (_, args): Promise<{
    success: boolean;
    captionsText: string | null;
    captionTracks: { language: string; name: string; isAutoGenerated: boolean }[];
    error: { type: string; message: string } | null;
  }> => {
    const { videoId } = args;

    // Validate video ID format
    if (!isValidVideoId(videoId)) {
      return {
        success: false,
        captionsText: null,
        captionTracks: [],
        error: {
          type: "INVALID_VIDEO_ID",
          message: "Invalid YouTube video ID format",
        },
      };
    }

    // Get API key from environment
    const apiKey = process.env.YOUTUBE_API_KEY;
    if (!apiKey) {
      console.warn("YOUTUBE_API_KEY not configured");
      return {
        success: false,
        captionsText: null,
        captionTracks: [],
        error: {
          type: "CONFIGURATION_ERROR",
          message: "YouTube API is not configured",
        },
      };
    }

    try {
      // Build API URL for captions list
      const url = new URL("https://www.googleapis.com/youtube/v3/captions");
      url.searchParams.set("videoId", videoId);
      url.searchParams.set("part", "snippet");
      url.searchParams.set("key", apiKey);

      // Fetch with timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000);

      const response = await fetch(url.toString(), {
        method: "GET",
        headers: {
          Accept: "application/json",
        },
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        // 403 errors for captions are common (requires auth for download)
        // Return success with empty captions rather than error
        if (response.status === 403) {
          return {
            success: true,
            captionsText: null,
            captionTracks: [],
            error: null,
          };
        }

        return {
          success: false,
          captionsText: null,
          captionTracks: [],
          error: {
            type: "FETCH_FAILED",
            message: `Failed to fetch captions: ${response.status}`,
          },
        };
      }

      const data: YouTubeCaptionsResponse = await response.json();

      // No captions available
      if (!data.items || data.items.length === 0) {
        return {
          success: true,
          captionsText: null,
          captionTracks: [],
          error: null,
        };
      }

      // Map caption tracks info
      const captionTracks = data.items.map((item) => ({
        language: item.snippet.language,
        name: item.snippet.name,
        isAutoGenerated: item.snippet.trackKind === "ASR",
      }));

      // Note: Actually downloading caption text requires OAuth.
      // For now, we return the track info and rely on video description.
      // Future enhancement: Use a third-party service or OAuth flow.
      return {
        success: true,
        captionsText: null, // Caption text download requires OAuth
        captionTracks,
        error: null,
      };
    } catch (error) {
      // Handle timeout
      if (error instanceof Error && error.name === "AbortError") {
        return {
          success: false,
          captionsText: null,
          captionTracks: [],
          error: {
            type: "TIMEOUT",
            message: "Request timed out. Please try again.",
          },
        };
      }

      console.error("Error fetching captions:", error);
      // Return success with no captions - captions are optional
      return {
        success: true,
        captionsText: null,
        captionTracks: [],
        error: null,
      };
    }
  },
});

/**
 * Alternative: Fetch captions using a third-party transcript service
 *
 * This function attempts to get video transcript text using publicly available
 * transcript data that YouTube makes available to video pages.
 */
export const fetchTranscriptText = action({
  args: {
    videoId: v.string(),
  },
  handler: async (_, args): Promise<{
    success: boolean;
    transcriptText: string | null;
    error: { type: string; message: string } | null;
  }> => {
    const { videoId } = args;

    if (!isValidVideoId(videoId)) {
      return {
        success: false,
        transcriptText: null,
        error: {
          type: "INVALID_VIDEO_ID",
          message: "Invalid YouTube video ID format",
        },
      };
    }

    try {
      // Attempt to fetch the video page and extract transcript data
      // This is a best-effort approach and may not always work
      const videoPageUrl = `https://www.youtube.com/watch?v=${videoId}`;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000);

      const response = await fetch(videoPageUrl, {
        method: "GET",
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          Accept: "text/html",
        },
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        return {
          success: true, // Transcript is optional
          transcriptText: null,
          error: null,
        };
      }

      const html = await response.text();

      // Try to find transcript/caption data in the page
      // YouTube embeds some caption data in the initial page load
      const captionTrackPattern = /"captionTracks":\s*(\[.*?\])/;
      const match = html.match(captionTrackPattern);

      if (!match) {
        return {
          success: true,
          transcriptText: null,
          error: null,
        };
      }

      // For now, return null as full transcript parsing is complex
      // The video description is typically sufficient for recipe extraction
      return {
        success: true,
        transcriptText: null,
        error: null,
      };
    } catch (error) {
      // Transcript fetch is optional, don't fail
      console.warn("Could not fetch transcript:", error);
      return {
        success: true,
        transcriptText: null,
        error: null,
      };
    }
  },
});
