/**
 * Auto-generated Convex API
 *
 * This file is automatically generated by Convex when running `npx convex dev`.
 * It provides type-safe references to your Convex functions.
 *
 * NOTE: This is a placeholder file for development/testing.
 * The actual file will be generated when the Convex project is initialized.
 */

// Placeholder API export
// This will be properly typed when generated by Convex
export const api = {
  recipes: {
    createRecipe: "recipes:createRecipe",
    updateRecipe: "recipes:updateRecipe",
    deleteRecipe: "recipes:deleteRecipe",
    toggleFavorite: "recipes:toggleFavorite",
    getRecipes: "recipes:getRecipes",
    getRecipeById: "recipes:getRecipeById",
    getFavoriteRecipes: "recipes:getFavoriteRecipes",
    saveFromYouTube: "recipes:saveFromYouTube",
  },
  physicalCookbooks: {
    createPhysicalCookbook: "physicalCookbooks:createPhysicalCookbook",
    updatePhysicalCookbook: "physicalCookbooks:updatePhysicalCookbook",
    deletePhysicalCookbook: "physicalCookbooks:deletePhysicalCookbook",
    getPhysicalCookbooks: "physicalCookbooks:getPhysicalCookbooks",
    getPhysicalCookbookById: "physicalCookbooks:getPhysicalCookbookById",
  },
  channels: {
    followChannel: "channels:followChannel",
    unfollowChannel: "channels:unfollowChannel",
    getFollowedChannels: "channels:getFollowedChannels",
    getFeaturedChannels: "channels:getFeaturedChannels",
    getChannelsByCategory: "channels:getChannelsByCategory",
    getAllChannels: "channels:getAllChannels",
    getChannelById: "channels:getChannelById",
    getChannelByYoutubeId: "channels:getChannelByYoutubeId",
    getFollowedChannelCount: "channels:getFollowedChannelCount",
    isFollowingChannel: "channels:isFollowingChannel",
    updateChannelData: "channels:updateChannelData",
    getFeed: "channels:getFeed",
  },
  actions: {
    extractRecipeFromUrl: {
      extractRecipeFromUrl: "actions/extractRecipeFromUrl:extractRecipeFromUrl",
    },
    youtube: {
      fetchVideoMetadata: {
        fetchVideoMetadata: "actions/youtube/fetchVideoMetadata:fetchVideoMetadata",
      },
      fetchCaptions: {
        fetchCaptions: "actions/youtube/fetchCaptions:fetchCaptions",
        fetchTranscriptText: "actions/youtube/fetchCaptions:fetchTranscriptText",
      },
      fetchChannelData: {
        fetchChannelData: "actions/youtube/fetchChannelData:fetchChannelData",
        searchChannels: "actions/youtube/fetchChannelData:searchChannels",
        getChannelVideos: "actions/youtube/fetchChannelData:getChannelVideos",
      },
      extractRecipeFromYouTube: {
        extractRecipeFromYouTube: "actions/youtube/extractRecipeFromYouTube:extractRecipeFromYouTube",
        downloadThumbnail: "actions/youtube/extractRecipeFromYouTube:downloadThumbnail",
      },
    },
  },
};
