/**
 * Auto-generated Convex data model types
 *
 * This file is automatically generated by Convex when running `npx convex dev`.
 * It provides TypeScript types for your database schema.
 *
 * NOTE: This is a placeholder file for development/testing.
 * The actual file will be generated when the Convex project is initialized.
 */

import { GenericDataModel, GenericDocument } from "convex/server";

// Placeholder DataModel type
// This will be properly typed when generated by Convex based on schema.ts
export type DataModel = GenericDataModel;
