/**
 * Auto-generated Convex server utilities
 *
 * This file is automatically generated by Convex when running `npx convex dev`.
 * It provides type-safe wrappers for defining mutations and queries.
 *
 * NOTE: This is a placeholder file for development/testing.
 * The actual file will be generated when the Convex project is initialized.
 */

import { GenericMutationCtx, GenericQueryCtx, FunctionReference } from "convex/server";
import { DataModel } from "./dataModel";

// Export mutation and query builders
// These will be properly typed when generated by Convex
export const mutation = <Args, Returns>(config: {
  args: Args;
  handler: (ctx: GenericMutationCtx<DataModel>, args: any) => Promise<Returns>;
}) => config;

export const query = <Args, Returns>(config: {
  args: Args;
  handler: (ctx: GenericQueryCtx<DataModel>, args: any) => Promise<Returns>;
}) => config;

// Re-export from convex/server for convenience
export type { GenericMutationCtx, GenericQueryCtx };
