/**
 * Category Assignment Utility
 *
 * Maps ingredient names to shopping list categories based on keyword matching.
 * Used during shopping list generation to auto-assign categories.
 */

/**
 * Shopping item category type
 */
export type ShoppingItemCategory =
  | "Produce"
  | "Meat & Seafood"
  | "Dairy & Eggs"
  | "Pantry"
  | "Bakery"
  | "Frozen"
  | "Beverages"
  | "Household";

/**
 * Category keyword mapping
 * Keywords are matched against ingredient names (case-insensitive)
 */
export const categoryKeywords: Record<ShoppingItemCategory, string[]> = {
  Produce: [
    // Vegetables
    "vegetable",
    "veggie",
    "salad",
    "lettuce",
    "spinach",
    "kale",
    "arugula",
    "cabbage",
    "broccoli",
    "cauliflower",
    "carrot",
    "celery",
    "cucumber",
    "tomato",
    "tomatoes",
    "onion",
    "garlic",
    "ginger",
    "potato",
    "potatoes",
    "sweet potato",
    "yam",
    "pepper",
    "bell pepper",
    "jalapeno",
    "zucchini",
    "squash",
    "eggplant",
    "mushroom",
    "asparagus",
    "green bean",
    "pea",
    "corn",
    "beet",
    "radish",
    "turnip",
    "leek",
    "scallion",
    "green onion",
    "shallot",
    // Fruits
    "fruit",
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "grapefruit",
    "berry",
    "berries",
    "strawberry",
    "blueberry",
    "raspberry",
    "blackberry",
    "grape",
    "melon",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "peach",
    "nectarine",
    "plum",
    "cherry",
    "cherries",
    "pear",
    "mango",
    "pineapple",
    "kiwi",
    "avocado",
    "coconut",
    // Fresh herbs
    "basil",
    "cilantro",
    "parsley",
    "mint",
    "rosemary",
    "thyme",
    "oregano",
    "dill",
    "chive",
    "sage",
    "tarragon",
    "fresh herb",
  ],

  "Meat & Seafood": [
    // Poultry
    "chicken",
    "turkey",
    "duck",
    "poultry",
    "breast",
    "thigh",
    "wing",
    "drumstick",
    // Beef
    "beef",
    "steak",
    "ground beef",
    "roast",
    "brisket",
    "ribeye",
    "sirloin",
    "filet",
    // Pork
    "pork",
    "bacon",
    "ham",
    "sausage",
    "pork chop",
    "tenderloin",
    "ribs",
    // Lamb
    "lamb",
    "mutton",
    // Seafood
    "fish",
    "salmon",
    "tuna",
    "cod",
    "tilapia",
    "halibut",
    "trout",
    "bass",
    "snapper",
    "mahi",
    "swordfish",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "scallop",
    "mussel",
    "clam",
    "oyster",
    "squid",
    "calamari",
    "octopus",
    "anchovy",
    "anchovies",
    "sardine",
    // Other
    "meat",
    "seafood",
    "deli",
  ],

  "Dairy & Eggs": [
    "milk",
    "cream",
    "half and half",
    "half-and-half",
    "heavy cream",
    "whipping cream",
    "sour cream",
    "buttermilk",
    "yogurt",
    "yoghurt",
    "kefir",
    "cheese",
    "cheddar",
    "mozzarella",
    "parmesan",
    "feta",
    "goat cheese",
    "brie",
    "cream cheese",
    "cottage cheese",
    "ricotta",
    "gruyere",
    "swiss",
    "provolone",
    "gouda",
    "blue cheese",
    "butter",
    "margarine",
    "egg",
    "eggs",
    "dairy",
  ],

  Pantry: [
    // Grains and pasta
    "rice",
    "pasta",
    "spaghetti",
    "penne",
    "linguine",
    "fettuccine",
    "noodle",
    "macaroni",
    "lasagna",
    "orzo",
    "couscous",
    "quinoa",
    "barley",
    "oat",
    "oats",
    "oatmeal",
    "cereal",
    "granola",
    // Flour and baking
    "flour",
    "sugar",
    "brown sugar",
    "powdered sugar",
    "baking powder",
    "baking soda",
    "yeast",
    "cornstarch",
    "cocoa",
    "chocolate chip",
    "vanilla",
    "extract",
    // Oils and vinegars
    "oil",
    "olive oil",
    "vegetable oil",
    "canola oil",
    "coconut oil",
    "sesame oil",
    "vinegar",
    "balsamic",
    "apple cider vinegar",
    "red wine vinegar",
    "white wine vinegar",
    // Canned goods
    "canned",
    "can of",
    "tomato sauce",
    "tomato paste",
    "diced tomatoes",
    "crushed tomatoes",
    "beans",
    "black beans",
    "kidney beans",
    "chickpeas",
    "lentils",
    "broth",
    "stock",
    "soup",
    // Condiments and sauces
    "ketchup",
    "mustard",
    "mayonnaise",
    "mayo",
    "soy sauce",
    "worcestershire",
    "hot sauce",
    "sriracha",
    "salsa",
    "bbq sauce",
    "teriyaki",
    "peanut butter",
    "almond butter",
    "jam",
    "jelly",
    "honey",
    "maple syrup",
    "molasses",
    // Spices and seasonings
    "salt",
    "pepper",
    "spice",
    "seasoning",
    "cumin",
    "paprika",
    "cinnamon",
    "nutmeg",
    "cloves",
    "allspice",
    "turmeric",
    "curry",
    "chili powder",
    "cayenne",
    "garlic powder",
    "onion powder",
    "italian seasoning",
    "bay leaf",
    "bay leaves",
    // Nuts and dried fruits
    "nut",
    "nuts",
    "almond",
    "walnut",
    "pecan",
    "cashew",
    "peanut",
    "pistachio",
    "pine nut",
    "dried",
    "raisin",
    "cranberries",
    "apricot",
    "date",
    "fig",
  ],

  Bakery: [
    "bread",
    "loaf",
    "baguette",
    "ciabatta",
    "sourdough",
    "roll",
    "rolls",
    "bun",
    "buns",
    "bagel",
    "croissant",
    "muffin",
    "english muffin",
    "pita",
    "naan",
    "flatbread",
    "tortilla",
    "wrap",
    "taco shell",
    "cracker",
    "breadcrumb",
    "panko",
    "crouton",
    "pastry",
    "pie crust",
    "pizza dough",
    "cake",
    "cookie",
    "donut",
    "doughnut",
  ],

  Frozen: [
    "frozen",
    "ice cream",
    "gelato",
    "sorbet",
    "popsicle",
    "frozen pizza",
    "frozen vegetable",
    "frozen fruit",
    "frozen dinner",
    "frozen meal",
    "fish stick",
    "chicken nugget",
    "waffle",
    "frozen waffle",
    "ice",
    "ice cube",
  ],

  Beverages: [
    "juice",
    "orange juice",
    "apple juice",
    "grape juice",
    "cranberry juice",
    "soda",
    "pop",
    "cola",
    "sprite",
    "ginger ale",
    "tonic",
    "seltzer",
    "sparkling water",
    "mineral water",
    "water",
    "bottled water",
    "coffee",
    "espresso",
    "tea",
    "green tea",
    "black tea",
    "herbal tea",
    "kombucha",
    "lemonade",
    "iced tea",
    "energy drink",
    "sports drink",
    "wine",
    "beer",
    "spirits",
    "liquor",
    "vodka",
    "rum",
    "whiskey",
    "bourbon",
    "gin",
    "tequila",
    "mixer",
  ],

  Household: [
    "paper towel",
    "napkin",
    "tissue",
    "toilet paper",
    "plastic wrap",
    "aluminum foil",
    "foil",
    "parchment paper",
    "wax paper",
    "ziplock",
    "storage bag",
    "trash bag",
    "garbage bag",
    "cleaning",
    "cleaner",
    "soap",
    "dish soap",
    "detergent",
    "laundry",
    "sponge",
    "scrubber",
    "bleach",
    "disinfectant",
    "pet food",
    "dog food",
    "cat food",
    "battery",
    "batteries",
    "light bulb",
    "candle",
  ],
};

/**
 * Assign a category to an ingredient based on keyword matching
 *
 * @param ingredientName - The name of the ingredient to categorize
 * @returns The assigned category, defaults to "Pantry" if no match
 */
export function assignCategory(ingredientName: string): ShoppingItemCategory {
  const normalizedName = ingredientName.toLowerCase().trim();

  // Check each category's keywords
  for (const [category, keywords] of Object.entries(categoryKeywords)) {
    for (const keyword of keywords) {
      if (normalizedName.includes(keyword.toLowerCase())) {
        return category as ShoppingItemCategory;
      }
    }
  }

  // Default to Pantry if no match found
  return "Pantry";
}

/**
 * Map from recipe ingredient category to shopping item category
 *
 * @param recipeCategory - The category from the recipe ingredient
 * @returns The corresponding shopping item category
 */
export function mapRecipeCategoryToShoppingCategory(
  recipeCategory: string
): ShoppingItemCategory {
  const mapping: Record<string, ShoppingItemCategory> = {
    meat: "Meat & Seafood",
    produce: "Produce",
    dairy: "Dairy & Eggs",
    pantry: "Pantry",
    spices: "Pantry",
    condiments: "Pantry",
    bread: "Bakery",
    other: "Pantry",
  };

  return mapping[recipeCategory] || "Pantry";
}
