/**
 * YouTube Data Types
 *
 * Shared type definitions for YouTube API integration and recipe extraction.
 */

/**
 * Confidence level for extracted recipe fields
 */
export type YouTubeExtractionConfidence = "high" | "medium" | "low";

/**
 * YouTube video metadata from API
 */
export interface YouTubeVideoMetadata {
  videoId: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  duration: string;
  durationSeconds: number;
  viewCount: number;
  publishedAt: string;
  channelId: string;
  channelTitle: string;
}

/**
 * YouTube channel data from API
 */
export interface YouTubeChannelData {
  channelId: string;
  name: string;
  avatarUrl: string;
  bannerUrl?: string;
  subscriberCount: number;
  description: string;
  videoCount: number;
}

/**
 * YouTube caption track info
 */
export interface YouTubeCaptionTrack {
  id: string;
  language: string;
  name: string;
  isAutoGenerated: boolean;
}

/**
 * Extracted recipe from YouTube video
 */
export interface YouTubeExtractedRecipe {
  title: string;
  ingredients: {
    name: string;
    quantity: number;
    unit: string;
    category: "meat" | "produce" | "dairy" | "pantry" | "spices" | "condiments" | "bread" | "other";
  }[];
  instructions: string[];
  prepTime: number;
  cookTime: number;
  servings: number;
  confidence: YouTubeExtractionConfidence;
  extractionNotes?: string;
}

/**
 * YouTube extraction result
 */
export interface YouTubeExtractionResult {
  success: boolean;
  recipe: YouTubeExtractedRecipe | null;
  metadata: YouTubeVideoMetadata | null;
  error?: {
    type: "FETCH_FAILED" | "NO_RECIPE_FOUND" | "EXTRACTION_FAILED" | "INVALID_VIDEO_ID" | "QUOTA_EXCEEDED";
    message: string;
  };
}

/**
 * Cached video data
 */
export interface CachedVideoData {
  videoId: string;
  metadata: YouTubeVideoMetadata;
  captionsText: string | null;
  cachedAt: number;
  expiresAt: number;
}

/**
 * Channel with following status
 */
export interface ChannelWithFollowStatus extends YouTubeChannelData {
  isFollowing: boolean;
  isFeatured: boolean;
  category: string;
}

/**
 * Video in feed format
 */
export interface FeedVideoData {
  videoId: string;
  title: string;
  thumbnailUrl: string;
  duration: string;
  viewCount: number;
  publishedAt: string;
  channelId: string;
  channelName: string;
  channelAvatarUrl: string;
}
